apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: health-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: health-api   # will match API service
  namespaceSelector:
    any: true
  endpoints:
  - port: http
    path: /metrics
    interval: 15s